// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Skadoosh.Common.DomainModels;

namespace Skadoosh.IPhone
{
	public partial class SelectSurveyController : UIViewController,IAppView
	{

		#region IAppView implementation

		public ViewModelBase VM { get; set;}

		#endregion
		public SelectSurveyController (IntPtr handle) : base (handle)
		{
		}
	}
}
