// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Skadoosh.IPhone
{
	public partial class HelpController : UIViewController
	{
		public HelpController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidLoad (){
		
			testTable.AllowsMultipleSelection = true;
		}
	}
}
