// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Skadoosh.Common.DomainModels;
using Skadoosh.Common.ViewModels;

namespace Skadoosh.IPhone
{
	public partial class HomeController : UIViewController,IAppView
	{
		#region IAppView implementation

		public ViewModelBase VM { get; set;}

		#endregion

		public HomeController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			btnLive.TouchUpInside += (s,a) => {
				var vm= new ParticipateLiveVM();
				var selectSurvey = (SelectSurveyController)this.Storyboard.InstantiateViewController("SelectSurvey");
				selectSurvey.VM=vm;
				this.PresentViewController(selectSurvey,true,null);
			};
			btnStatic.TouchUpInside += (s,a) => {
				var vm= new ParticipateStaticVM();
				var selectSurvey = (SelectSurveyController)this.Storyboard.InstantiateViewController("SelectSurvey");
				selectSurvey.VM=vm;
				this.PresentViewController(selectSurvey,true,null);
			};
		}
	}
}
