// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Skadoosh.Common.DomainModels;

namespace Skadoosh.IPhone
{
	public partial class SelectSurvey : UIViewController, IAppView
	{
		#region IAppView implementation

		public ViewModelBase VM { get; set;}

		#endregion

		public SelectSurvey (IntPtr handle) : base (handle)
		{
		}
	}
}
