// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Skadoosh.Common.DomainModels;
using Skadoosh.Common.ViewModels;

namespace Skadoosh.IPhone
{
	public partial class SelectSurveyController : UIViewController,IAppView
	{
		private LoadingOverlay loadingOverlay;

		#region IAppView implementation

		public ViewModelBase VM { get; set;}

		#endregion
		public SelectSurveyController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad (){

			btnStart.TouchUpInside+= async(s,a)=>{
				if(VM is ParticipateLiveVM){
					loadingOverlay = new LoadingOverlay (UIScreen.MainScreen.Bounds);
					View.Add (loadingOverlay);
					//var result = await ((ParticipateLiveVM)VM).FindSurveyCurrentChannel();
					//loadingOverlay.Hide();
					/*
					if(result!=1){

					}
					else{

					}*/
				}
				else{
					var result =  await ((ParticipateStaticVM)VM).FindSurveyCurrentChannel();
					if(result!=1){

					}
					else{

					}
				}
			};

		}

		public override void TouchesBegan (NSSet touches, UIEvent evt)
		{
			base.TouchesBegan (touches, evt);
			this.View.EndEditing(true);
		}
	}
}
