// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Skadoosh.IPhone
{
	public partial class StaticSurveyController : UIViewController
	{
		public StaticSurveyController (IntPtr handle) : base (handle)
		{
		}
	}
}
