#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Skadoosh.Droid.Resource", IsApplication=true)]

namespace Skadoosh.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int pressed_skadoosh = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_skadoosh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_skadoosh = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_skadoosh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_skadoosh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_skadoosh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_skadoosh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_skadoosh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_skadoosh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_pressed_skadoosh = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_skadoosh = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_skadoosh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_skadoosh = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_launcher = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int list_focused_skadoosh = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int menu_dropdown_panel_skadoosh = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int PandaBack = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pressed_background_skadoosh = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int progress_bg_skadoosh = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int progress_horizontal_skadoosh = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int progress_primary_skadoosh = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress_secondary_skadoosh = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int selectable_background_skadoosh = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int spinner_ab_default_skadoosh = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int spinner_ab_disabled_skadoosh = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int spinner_ab_focused_skadoosh = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int spinner_ab_pressed_skadoosh = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int spinner_background_ab_skadoosh = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int splash640_960 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tab_indicator_ab_skadoosh = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int tab_selected_focused_skadoosh = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int tab_selected_pressed_skadoosh = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tab_selected_skadoosh = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_unselected_focused_skadoosh = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_unselected_pressed_skadoosh = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_unselected_skadoosh = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MyButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar_Solid_Skadoosh = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Transparent_Skadoosh = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ActionBarTabStyle_Skadoosh = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ActionButton_CloseMode_Skadoosh = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int DropDownListView_Skadoosh = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DropDownNav_Skadoosh = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PopupMenu_Skadoosh = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ProgressBar_Skadoosh = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Skadoosh = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int Theme_Skadoosh_Widget = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
