#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("skadoosh.DroidPhone.Resource", IsApplication=true)]

namespace skadoosh.DroidPhone
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int divider = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int tabLayout = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int tabStripEnabled = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int tabStripLeft = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int tabStripRight = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int pressed_skadoosh = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int skadooshOrange = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int alert_dialog_button_bar_height = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int alert_dialog_title_height = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tab_host_default_height = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_skadoosh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_skadoosh = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_skadoosh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_skadoosh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_skadoosh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_skadoosh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int activated_background_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_default_skadoosh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_focused_skadoosh = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_skadoosh = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_skadoosh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_check_holo_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_check_off_disabled_focused_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_check_off_disabled_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_check_off_focused_holo_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_check_off_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_check_off_pressed_holo_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_check_on_disabled_focused_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_check_on_disabled_holo_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_check_on_focused_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int btn_check_on_holo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int btn_check_on_pressed_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int btn_default_disabled_focused_holo_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int btn_default_disabled_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int btn_default_focused_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int btn_default_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int btn_default_normal_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int btn_default_pressed_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int btn_radio_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int btn_radio_off_disabled_focused_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int btn_radio_off_disabled_holo_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int btn_radio_off_focused_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int btn_radio_off_holo_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int btn_radio_off_pressed_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int btn_radio_on_disabled_focused_holo_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int btn_radio_on_disabled_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int btn_radio_on_focused_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int btn_radio_on_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int btn_radio_on_pressed_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int btn_rating_star_off_focused_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int btn_rating_star_off_normal_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int btn_rating_star_off_pressed_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int btn_rating_star_on_focused_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int btn_rating_star_on_normal_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int btn_rating_star_on_pressed_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int btn_toggle_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int btn_toggle_off_disabled_focused_holo_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int btn_toggle_off_disabled_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int btn_toggle_off_focused_holo_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int btn_toggle_off_normal_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int btn_toggle_off_pressed_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int btn_toggle_on_disabled_focused_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int btn_toggle_on_disabled_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int btn_toggle_on_focused_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int btn_toggle_on_normal_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int btn_toggle_on_pressed_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int cab_background_bottom_skadoosh = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int cab_background_top_skadoosh = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int edit_text_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int fastscroll_thumb_default_holo = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int fastscroll_thumb_holo = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int fastscroll_thumb_pressed_holo = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_launcher = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Icon = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int item_background_holo_light = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int list_activated_holo = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int list_focused_holo = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int list_focused_skadoosh = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int list_longpressed_holo = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int list_pressed_holo_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int list_selector_background_transition_holo_light = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int list_selector_disabled_holo_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int list_selector_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int liveSurvey = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int menu_dropdown_panel_skadoosh = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int numberpicker_selection_divider = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int PandaBack = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int pressed_background_skadoosh = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int progress_bg_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int progress_bg_skadoosh = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int progress_horizontal_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int progress_horizontal_skadoosh = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int progress_indeterminate_horizontal_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int progress_primary_holo_light = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int progress_primary_skadoosh = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int progress_secondary_holo_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int progress_secondary_skadoosh = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int progressbar_indeterminate_holo1 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int progressbar_indeterminate_holo2 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int progressbar_indeterminate_holo3 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int progressbar_indeterminate_holo4 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int progressbar_indeterminate_holo5 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int progressbar_indeterminate_holo6 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int progressbar_indeterminate_holo7 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int progressbar_indeterminate_holo8 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int rate_star_big_half_holo_light = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int rate_star_big_off_holo_light = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int rate_star_big_on_holo_light = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int rate_star_small_half_holo_light = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int rate_star_small_off_holo_light = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int rate_star_small_on_holo_light = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ratingbar_full_empty_holo_light = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ratingbar_full_filled_holo_light = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ratingbar_full_holo_light = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ratingbar_holo_light = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ratingbar_small_holo_light = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int scrubber_control_disabled_holo = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int scrubber_control_focused_holo = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int scrubber_control_normal_holo = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int scrubber_control_pressed_holo = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int scrubber_control_selector_holo_light = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int scrubber_primary_holo = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int scrubber_progress_horizontal_holo_light = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int scrubber_secondary_holo = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int scrubber_track_holo_light = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int selectable_background_skadoosh = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int spinner_ab_default_skadoosh = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int spinner_ab_disabled_skadoosh = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int spinner_ab_focused_skadoosh = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int spinner_ab_pressed_skadoosh = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int spinner_background_ab_skadoosh = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int spinner_background_holo_light = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int spinner_default_holo_light = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int spinner_disabled_holo_light = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int spinner_focused_holo_light = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int spinner_pressed_holo_light = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int splash640_960 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int staticSurvey = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int storeKadoosh = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int switch_bg_disabled_holo_light = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int switch_bg_focused_holo_light = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int switch_bg_holo_light = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int switch_inner_holo_light = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int switch_thumb_activated_holo_light = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int switch_thumb_disabled_holo_light = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int switch_thumb_holo_light = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int switch_thumb_pressed_holo_light = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int switch_track_holo_light = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int tab_indicator_ab_skadoosh = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int tab_indicator_holo = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int tab_selected_focused_holo = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int tab_selected_focused_skadoosh = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int tab_selected_holo = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int tab_selected_pressed_holo = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int tab_selected_pressed_skadoosh = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int tab_selected_skadoosh = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int tab_unselected_focused_holo = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int tab_unselected_focused_skadoosh = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int tab_unselected_holo = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int tab_unselected_pressed_holo = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int tab_unselected_pressed_skadoosh = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int tab_unselected_skadoosh = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int textfield_activated_holo_light = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int textfield_default_holo_light = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int textfield_disabled_focused_holo_light = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int textfield_disabled_holo_light = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int textfield_focused_holo_light = 2130837660;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int HelpFrame = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int HomeFrame = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int LiveSurvey = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int SelectFrame = 2131230732;
			
			// aapt resource value: 0x7f080011
			public const int StaticSurvey = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int absoluteLayout1 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int absoluteLayout2 = 2131230727;
			
			// aapt resource value: 0x7f080015
			public const int btnBack = 2131230741;
			
			// aapt resource value: 0x7f080006
			public const int btnLive = 2131230726;
			
			// aapt resource value: 0x7f080017
			public const int btnNext = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int btnQuit = 2131230742;
			
			// aapt resource value: 0x7f080010
			public const int btnStart = 2131230736;
			
			// aapt resource value: 0x7f080008
			public const int btnStatic = 2131230728;
			
			// aapt resource value: 0x7f080014
			public const int linearLayout1 = 2131230740;
			
			// aapt resource value: 0x7f08000b
			public const int liveOptionLayout = 2131230731;
			
			// aapt resource value: 0x7f080013
			public const int optionLayout = 2131230739;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int textView2 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int textView3 = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int txtFirstName = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int txtLastName = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int txtLiveQuestion = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int txtQuesationText = 2131230738;
			
			// aapt resource value: 0x7f08000d
			public const int txtSurveyCode = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Help = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LiveSurvey = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SelectSurvey = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StaticSurvey = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int ActionBar_Solid_skadoosh = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ActionBar_Transparent_skadoosh = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int ActionBarTabStyle_skadoosh = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int ActionButton_CloseMode_skadoosh = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int AlertDialogCustom = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int AutoCompleteTextViewskadoosh = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int Buttonskadoosh = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int CheckBoxskadoosh = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int DropDownListView_skadoosh = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int DropDownNav_skadoosh = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int EditTextskadoosh = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int ImageButtonskadoosh = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int ListViewskadoosh = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int ListViewskadoosh_White = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int NumberPickerskadoosh = 2131099680;
			
			// aapt resource value: 0x7f060005
			public const int PopupMenu_skadoosh = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int ProgressBar_skadoosh = 2131099657;
			
			// aapt resource value: 0x7f060017
			public const int ProgressBarskadoosh = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int RadioButtonskadoosh = 2131099663;
			
			// aapt resource value: 0x7f06001a
			public const int RatingBarBigskadoosh = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int RatingBarSmallskadoosh = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int RatingBarskadoosh = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int SeekBarskadoosh = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int SpinnerDropDownItemskadoosh = 2131099668;
			
			// aapt resource value: 0x7f06001f
			public const int SpinnerItemskadoosh = 2131099679;
			
			// aapt resource value: 0x7f060012
			public const int Spinnerskadoosh = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int Spinnerskadoosh_DropDown = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int TabTextskadoosh = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int Tabskadoosh = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_skadoosh = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int Theme_skadoosh_Widget = 2131099659;
			
			// aapt resource value: 0x7f06001c
			public const int Toggleskadoosh = 2131099676;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TabWidget = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public const int TabWidget_divider = 0;
			
			// aapt resource value: 4
			public const int TabWidget_tabLayout = 4;
			
			// aapt resource value: 1
			public const int TabWidget_tabStripEnabled = 1;
			
			// aapt resource value: 2
			public const int TabWidget_tabStripLeft = 2;
			
			// aapt resource value: 3
			public const int TabWidget_tabStripRight = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
