// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Skadoosh.MonoTouch
{
	public partial class LiveSurveyViewer : UIViewController
	{
		public LiveSurveyViewer (IntPtr handle) : base (handle)
		{
		}
	}
}
